#!/bin/bash
# A git hook that run composer validate if composer.json changes.

case "${1}" in
    --about )
        echo -n "Runs a git composer validate command before a commit."
        ;;
    * )
        if [[ -f "composer.json" ]]; then
            if git rev-parse --verify HEAD >/dev/null 2>&1
            then
                against=HEAD
            else
                # Initial commit: diff against an empty tree object
                against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
            fi

            CHANGED=`git diff-index --name-status $against -- composer.json | wc -l`
            if [ $CHANGED -gt 0 ];
            then
                composer validate
                isValid=$?
                if [ $isValid -ne 0 ]
                then
                    exit $isValid
                fi
            fi
        fi

        ;;
esac
